### ISSUE TITLE
authorization context is broken in 0.4.x version 

### ISSUE THREAD

**Issue by saiqulhaq** [palkan/action_policy#100]
### Tell us about your environment

Ruby 2.4.7
Rails 6.0.2.1
Action Policy 0.4.3

### What did you do?

I upgraded ActionPolicy from 0.3.x and Rails 6.0.1 to newer version

### What did you expect to happen?

my app works as usual

### What actually happened?

there is error with authorization_context method

so I have

```
authorize :current_store
verify_authorized
```

on my base controller

but current_store is nil in `athorization_context[:current_store]`

so I have to add `authorization_context[:current_store] = current_store` in `before_action` callback to manually set current_store

**Comment by palkan** [comment]
Have you tried downgrading action_policy to 0.3.x but keeping Rails at 6? (just to eliminate the Rails factor).

**Comment by saiqulhaq** [comment]
I just downgraded to 0.3.4, it works fine now

**Comment by trentclowater** [comment]
I had the same problem immediately after upgrading from ActionPolicy 0.3.4 to any 0.4.x version (Ruby 2.6.3, Rails 6.0.2.1). Returning to 0.3.4 fixed the problem. So it seems the problem was introduced in 0.4.0.

However, I have two models that are configured almost identically (or at least I can't find anything that should make a difference) and only the tests for one were failing.

**Comment by palkan** [comment]
@trentclowater thanks for sharing!

> However, I have two models that are configured almost identically (or at least I can't find anything that should make a difference) and only the tests for one were failing.

Could you provide an example of your controllers/policies?

**Comment by palkan** [comment]
Hey @saiqulhaq @trentclowater!

I've added a [bug report template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb), which should help to create a simple reproduction script. Could you please try to do that?

**Comment by saiqulhaq** [comment]
Hi @palkan 

finally I found the cause

this is my BaseController

```ruby
class Stores::BaseController < ApplicationController
  attr_reader :current_store
  helper_method :current_store

  before_action :find_current_store

  def find_current_store(id = nil)
    @current_store = xxx
  end

  authorize :current_store
  verify_authorized
end
```

in version 0.3.4, `before_action :find_current_store` is executed before this method called https://github.com/palkan/action_policy/blob/38ea2852d7f67c572cf0136c34845e420caf0c24/lib/action_policy/behaviour.rb#L51

but in version 0.4.3, my `before_action` is not called first, that's why in `authorization_context`, `:current_store` context is `nil`

**Comment by palkan** [comment]
@saiqulhaq Interesting. The execution of `before_action` blocks is out of Action Policy responsibility.

Can you show me a full stack trace of the `allowed_to?` call? Where is it called from?

**Comment by saiqulhaq** [comment]
in single request, I call `authorize` many times

and the authorization context is memoized
so its value is not updated when I call next `authorize` method

to fix this, I updated `lib/action_policy/behaviour.rb` line number 62 to be like this:

```ruby
    def authorization_context
      @__authorization_context = self.class.authorization_targets
        .each_with_object({}) do |(key, meth), obj|
        obj[key] = send(meth) if obj[key].nil?
      end
      @__authorization_context
    end
```

**Comment by palkan** [comment]
> in single request, I call authorize many times
and the authorization context is memoized
so its value is not updated when I call next authorize method

You mean that you have different contexts for different `authorize` calls?
Action Policy assumes that a single request is happening within the same context (that's why we memoize it).

If you need different contexts, you should provide the context explicitly via `context: ...` option, e.g.:

```ruby
authorize! obj, to: smth?, context: {current_store: current_store}
```

As far as I understand, in your case the actual problem is that there is another `before_action` callback which calls `authorize!` or `allowed_to?` before the `find_current_store` callback.

Then we can fix it either by adding `prepend: true` to `before_action :find_current_store` to make this callback fire before others, or, which is better, to remove the callback at all and use memoization:

```ruby
def current_store
   return @current_store if instance_variable_defined?(:@current_store)
  @current_store = xxx
end
```

**Comment by palkan** [comment]
@saiqulhaq Have you figured this out?

**Comment by saiqulhaq** [comment]
sorry I didn't update
finally I added explicit context to every authorization code
