### ISSUE TITLE
Bug with injecting helpers to `ActionController::Api` based class

### ISSUE THREAD

**Issue by roman-dubrovsky** [palkan/action_policy#106]
**Action Policy Version:** 0.4.3

On generating Rails API application and using `ActionController::Api` controller (instead of `ActionController::Base` controller), ActionPolicy can't inject helpers to our base `ApplicationController`. 

It happens because the railtie injects helpers to `ActionController::Base`

https://github.com/palkan/action_policy/blob/38ea2852d7f67c572cf0136c34845e420caf0c24/lib/action_policy/railtie.rb#L88-L92

but this controller isn't a base class for `ActionController::Api`  class

https://github.com/rails/rails/blob/6d0895a4894724e1a923a514daad8fb3c9ac2c28/actionpack/lib/action_controller/api.rb#L89-L90

My proposal is injecting code to the `AbstractController::Base` class in the railtie file (or at least  `ActionController::Metal` class which is parrent for `ActionController::Base` and `ActionController::Api` classess).

Thank you for your attention.

**Comment by palkan** [comment]
We cover this in the documentation: https://actionpolicy.evilmartians.io/#/rails?id=usage-with-api-and-metal-controllers

The goal of the automatic configuration is to simplify the most common use cases.
Extending abstract or metal automatically doesn't seem to be a good idea, 'cause users assume them to be _clear_.

Properly extending API controller would only work in Rails 5.2+ (which has `:action_controller_api` load hook). That's why we do not support it right now: users still need to configure Action Policy manually depending on the version, which is more confusing than "alway configure manually".
