### ISSUE TITLE
Clearing per-instance rule cache

### ISSUE THREAD

**Issue by calebuharrison** [palkan/action_policy#110]
Hi, thanks for this fantastic project!

Is there a way to clear the per-instance (local) rule cache of a policy? I have my policies configured with per-attribute read/write rules for each resource that my API serves, and persistence operations on those resources often change the expected results of those rules, which necessitates clearing the cache. How would I go about doing this?

**Comment by palkan** [comment]
Thank you!

> I have my policies configured with per-attribute read/write rules for each resource that my API serves, and persistence operations on those resources often change the expected results of those rules

I think, in this case you need to invalidate the policy objects cache (per-thread or per-behavior memoization). That would give you a _clean_ policy object with an empty rules cache.

In most cases, that should happen automatically, since behavior/thread memoization uses cache keys. Do you records implement `#cache_key` method? For example, Active Record's `#cache_key` method uses `#updated_at` under the hood, thus updating the key after every `#save` operation.

Are you using `authorize!` and `allowed_to?` methods or initialize policy objects manually?

**Comment by calebuharrison** [comment]
I discovered my issue!

I was using the `apply` method to compose rules when I should have been using the `check?` alias for `allowed_to?`. As soon as I made that swap in all of my policies, the tests turned green.

Thanks for your help!
