### ISSUE TITLE
instrumentation.rb namespacing?

### ISSUE THREAD

**Issue by joshRpowell** [palkan/action_policy#129]
### Tell us about your environment

**Ruby Version:** 2.7.1

**Framework Version (Rails, whatever):** Rails 6.0.3.2

**Action Policy Version:** 0.4.4

**Reproduction Script:** Use [this template](https://github.com/palkan/action_policy/blob/master/.github/bug_report_template.rb) to
create a standalone reproduction script. That would help us to fix the problem quicker. Thanks!

### What did you do?

Reviewed the kwarg update:

<img width="648" alt="Screen Shot 2020-08-22 at 2 00 52 PM" src="https://user-images.githubusercontent.com/6732638/90962695-f1630780-e47f-11ea-929b-a0634b8100a3.png">

### What did you expect to happen?

Expected to see this file path `../action_policy/rails/policy/instrumentation.rb`

coincide with this module hierarchy:

```ruby
module ActionPolicy 
  module Rails
    module Policy
      module Instrumentation
```  

### What actually happened?

`instrumentation.rb` has the following:

```ruby
module ActionPolicy 
  module Policy
    module Rails
      module Instrumentation
```  

This came to my attention after bumping to 2.7 and trying to monkey patch the module locally.

**Comment by palkan** [comment]
The reason for this difference is the following: on one hand we want everything related to Rails kept under `action_policy/rails`; on the other hand we want Rails policy modules to have access to the `ActionPolicy::Policy` scope for constant resolution (e.g., to use `ExecutionResult` instead of `ActionPolicy::ExecutionResult`), similarly to other policy extensions.
