### ISSUE TITLE
authorize! with no arguments not resolving namespace

### ISSUE THREAD

**Issue by jacobwalkr** [palkan/action_policy#14]
### Tell us about your environment

**Ruby Version:**
2.4.3

**Framework Version (Rails, whatever):**
Rails 5.2.0.rc2

**Action Policy Version:**
0.1.4

### What did you do?
Called `authorize!` from `Groups::AnnouncementsController#show` (`/app/controllers/groups/announcements_controller.rb`) with no arguments.

### What did you expect to happen?
For the policy `Groups::AnnouncementPolicy` (`/app/policies/groups/announcement_policy.rb`) or `Group::AnnouncementPolicy` (`/app/policies/group/announcement_policy.rb`) (tried both) to be found and to authorise `#show`.

### What actually happened?
```ruby
ActionPolicy::NotFound in Groups::AnnouncementsController#show
Couldn't find policy class for Announcement(...)
```

Moving the policy out of a directory and calling it `::AnnouncementPolicy` works just fine, but I'd rather keep the namespace :)

For reference, the policy as-is:

```ruby
class AnnouncementPolicy < ApplicationPolicy
  def show?
    true
  end
end
```

**Comment by palkan** [comment]
> For the policy Groups::AnnouncementPolicy (/app/policies/groups/announcement_policy.rb) or Group::AnnouncementPolicy (/app/policies/group/announcement_policy.rb) (tried both) to be found and to authorise #show.

Should work with `groups/announcement_policy.rb`, not `group/announcement_policy.rb`.

I've tried to reproduce it here: https://github.com/palkan/action_policy/tree/repro/14/tmp/issue14-app.

Works as expected. How does it differ from your setup?

Also, while I was trying to reproduce the problem I also faced the same issue; it turned out that I had a type in policy file name.

Could you try to run `"Groups::AnnouncementPolicy".safe_constantize"` from your `rails c`? Does it return a class or `nil`?
