### ISSUE TITLE
What is the alternative of verify_policy_scoped from Pundit?

### ISSUE THREAD

**Issue by mabras** [palkan/action_policy#143]
I am using authorized_scope in `index` action. Using `verify_authorized` will throw an exception `ActionPolicy::UnauthorizedAction`. In Pundit there is `verify_policy_scoped`. Is there an alternative for it in AP.

Thanks,

**Comment by palkan** [comment]
There is no built-in alternative. The reason is that scoping could be applied multiple times (pretty often), and that's OK; so, such verification could bring fake confidence (one collection is scoped, another one lacks scoping—verification passes).

I'd suggest writing [unit-tests](https://actionpolicy.evilmartians.io/#/testing?id=testing-scoping) instead.
