### ISSUE TITLE
Can't alias `create?` to `manage?`

### ISSUE THREAD

**Issue by casperbrike** [palkan/action_policy#250]
### Tell us about your environment

**Ruby Version:** 3.1.3p185

**Framework Version (Rails, whatever):** Rails v7.0.5.1

**Action Policy Version:** 0.6.0

**Reproduction Script:** 
```ruby
require 'action_policy'

class MyPolicy < ActionPolicy::Base
  alias_rule :create?, to: :manage?

  def manage?
    true
  end
end

policy = MyPolicy.new(user: {})

puts "manage? => #{policy.manage?}"
puts "create? => #{policy.create?}"

```

### What did you do?
I tried to make `create?` an alias to `manage?`

### What did you expect to happen?
`create?` returns the same result as `manage?`

### What actually happened?
`create?` always returns false (see Reproduction script):
```
manage? => true
create? => false
```

**Comment by palkan** [comment]
`alias_rule` is different from Ruby's alias (see [docs](https://actionpolicy.evilmartians.io/#/aliases)).

It's purpose is to route called rules to actual methods; so, `alias_rule` defines an alias for `authorize!` and `allowed_to?` calls, not direct method calls.

You can see the difference if you call `apply(rule)` instead of calling the methods directly:

```ruby
puts "manage? => #{policy.apply(:manage?)}" #=> true
puts "create? => #{policy.apply(:create?)}" #=> true
```
