### ISSUE TITLE
doc examples unclear: singular or plural?

### ISSUE THREAD

**Issue by fwolfst** [palkan/action_policy#59]
### Tell us about your environment

**Framework Version (Rails, whatever):**
Rails 5.2.2

**Action Policy Version:**
0.2.4

### What did you do?

Read the docs

### What did you expect to happen?

Consistency, or mentioning of plural vs singular usage of `Post(s)Policy` in the introductory examples.

### What actually happened?

After interpreting the examples I became confused.

While it could make sense (and probably is mentioned deeper down in the doc), that
`authorize! (@users = User.all)` authorizes with the `UsersPolicy` (note the `s`s), it apparently tries to do so against `UserPolicy`.

If you want, I can adjust the examples and write a line that in principle plural naming is possible, but the infered model name is singular and thus automatic lookup will not work. Or maybe, I miss something.

**Comment by palkan** [comment]
> If you want, I can adjust the examples and write a line that in principle plural naming is possible, but the infered model name is singular and thus automatic lookup will not work

We have a doc article on the policies lookup: https://actionpolicy.evilmartians.io/#/lookup_chain.

Plural form is only possible when the policy name is explicitly defined for the class (via `.policy_name` or `.policy_class`).

Looks like the docs contain some typos (plural instead of singular).

It would be great if you propose a PR with fixes. And, maybe, it makes sense to add a link to the policy lookup doc somewhere in the Quick Start.
