### ISSUE TITLE
default_rule and manage? does not work as expected

### ISSUE THREAD

**Issue by fwolfst** [palkan/action_policy#67]
### Tell us about your environment

**Ruby Version:  2.6.1**

**Framework Version (Rails, whatever): Rails 5.2.2**

**Action Policy Version: 0.3.0**

### What did you do?
I have a rather boring Ruby on Rails application with following setup:

```ruby
# custom "base" controller
class NeserituController < ApplicationController
  # ...
  verify_authorized if !Rails.env.production?
  # ...
  rescue_from ActionPolicy::Unauthorized do |exception|
      redirect_back fallback_location: root_path,
        flash: {alert: :not_authorized }
    end
  # ...
  end
```
```ruby
# application_policy.rb
class ApplicationPolicy < ActionPolicy::Base
  authorize :user, through: :current_user, allow_nil: true
end
```

```ruby
# seminar_kind_policy.rb
class SeminarKindPolicy < ApplicationPolicy
  #default_rule :manage? #(doesnt make a difference if uncommented)
  def manage?
    user.admin?
  end
end
```
```ruby
class Admin::SeminarKindsController < NeserituController
  before_action :authenticate_user!           

  def index
    @seminar_kinds = SeminarKind.all                         
    authorize!                                                     
  end  
```

### What did you expect to happen?

According to https://actionpolicy.evilmartians.io/#/aliases , the controller should ask the policy if `index?` is good to go, which should resolve to `manage?`. Logged in as an admin-user (`user.admin == true`), I should be able to visit the path and see the correct view.

### What actually happened?

But when visiting the relevant path to the index-action of last controller (`admin_seminar_kinds_path`), I get redirected and a "not authorized" message.
If I rename the `manage?` definition in the policy to `index?`, or manually create an alias (`alias_rule :index?, to: :manage?`) it works.

**Comment by fwolfst** [comment]
I believe the "problem" is that I do not pass a record to the `authorize!` call. If I pass in a `SeminarKind.new` it works as expected. Bottom line: `default_rule` only applies to policy lookup if a record is given, otherwise you have to define aliases manually.

**Comment by palkan** [comment]
> default_rule only applies to policy lookup if a record is given, otherwise you have to define aliases manually.

Aliases and default rules do not depend on the record.

The problem is caused by the following:
- Alias resolution is implemented here https://github.com/palkan/action_policy/blob/98095adbe886d2d61a16cee4e8b56549b7f1e1e1/lib/action_policy/policy/aliases.rb#L31-L36

Note that it checks `respond_to?(activity)` and fallbacks to the default rule only if no method defined.

- `Defaults` module (which is included by default into `ActionPolicy::Base`) defines **three rules**: https://github.com/palkan/action_policy/blob/98095adbe886d2d61a16cee4e8b56549b7f1e1e1/lib/action_policy/policy/defaults.rb#L24-L34

Thus, `index?` is defined method, and according to [the resolution algorithm](https://actionpolicy.evilmartians.io/#/aliases?id=rule-resolution-with-subclasses) we do not fallback to the default rule.

We should add a note about this caveat to the docs.

**Comment by fwolfst** [comment]
Yes, my bad. I passed in a record of different type (not `SeminarKind`) for which the Policy allowed me an `index?`. I'll see if I can get on to a PR for the doc within the next days.
