### ISSUE TITLE
Policy lookup does not work with SimpleDelegator

### ISSUE THREAD

**Issue by pablocrivella** [palkan/action_policy#73]
### Tell us about your environment

**Ruby Version:**

2.6.3

**Framework Version (Rails, whatever):**

None.

**Action Policy Version:**

0.3.1

### What did you do?

Used `SimpleDelegator` to decorate an object and send it to the policy.

### What did you expect to happen?

Expect the correct policy to be resolved.

### What actually happened?

```
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/action_policy-0.3.1/lib/action_policy.rb:32:in `lookup': Couldn't find policy class for #<Post:0x00007fe5234431c0> (ActionPolicy::NotFound)
```

### How to reproduce?

```ruby
#!/usr/bin/env ruby

require "bundler/inline"

gemfile true do
  source "https://rubygems.org"

  gem "action_policy"
end

require "action_policy"

class User
end

class Post
end

class PostPolicy < ActionPolicy::Base
  def update?
    true
  end
end

class PostDecorator < SimpleDelegator
end

class PostUpdateAction
  include ActionPolicy::Behaviour

  # provide authorization subject (performer)
  authorize :user

  attr_reader :user

  def initialize(user)
    @user = user
  end

  def call(post)
    authorize! post, to: :update?
  end
end

user = User.new
post = Post.new

puts PostUpdateAction.new(user).call(post)

post_decorator = PostDecorator.new(post)

puts PostUpdateAction.new(user).call(post_decorator)

```

**Comment by palkan** [comment]
Hey @pablocrivella,

This is not the expected behaviour: policy lookup relies on the object class (it's name or `.policy_name` / `.policy_class` methods, see [docs](https://actionpolicy.evilmartians.io/#/lookup_chain)).

In your case, the class of the object is `PostDecorator` (not `Post`) and we can only infer from it the `PostDecoratorPolicy`, which doesn't exist—and we fail.

We (from the library perspective) cannot know beforehand, whether you wan to use `PostDecoratorPolicy` or `PostPolicy`, that should be decide by the developer.

One workaround is to pass the underlying object to the lookup chain instead of a decorator. See, for example, the Draper use-case: https://actionpolicy.evilmartians.io/#/./decorators.

Another workaround is to specify the policy name explicitly:

```ruby
class PostDecorator < SimpleDelegator
  def self.policy_name
    "PostPolicy"
  end
end
```

**Comment by pablocrivella** [comment]
Understood! Thanks for your explanation @palkan :)
