### ISSUE TITLE
Apply rule defaults and aliases more thoroughly?

### ISSUE THREAD

**Issue by jfouse** [palkan/action_policy#79]
I'm wondering if there's a reason not to have Core#\_\_apply\_\_ call resolve_rule before public_send, like this:

```ruby
def __apply__(rule)
  rule = resolve_rule(rule)
  public_send(rule)
end
```

This would support default rules and rule aliases across the board instead of just for controller actions, including calling check?/allowed_to? from within policies, policy.apply from anywhere, and supporting 3rd party gems (like ActiveAdmin) that may use their own mechanisms to authorize controller actions.

**Comment by palkan** [comment]
Yep, there is a reason: to make direct policy usage explicit thus simplifying the policy classes themselves; we try to keep policy classes as PORO as possible and avoid any automagic inference/resolution.
And that's why we have a concept of [_behaviour_](https://actionpolicy.evilmartians.io/#/behaviour): it acts as an adapter between the authorization context and the policy.

> policy.apply from anywhere, and supporting 3rd party gems (like ActiveAdmin)

Ideally, you shouldn't call `policy.apply` directly, you should always use Behavior.

> including calling check?/allowed_to? from within policies

That probably makes sense. Especially in the context of the failure reasons.
